from pathlib import Path

p = Path('tests/probe/probe_hooks.cpp')
s = p.read_text(encoding='utf-8')

def rep(old, new):
    global s
    if s.count(old) != 1:
        raise SystemExit(f'target count {s.count(old)} for {old[:80]!r}')
    s = s.replace(old, new)

rep('#include "colorfix_hooks.hpp"\n', '#include "colorfix_hooks.hpp"\n#include "uxtheme_observer.hpp"\n')
rep('namespace cfh = colorfix::hooks;\nusing cfh::HookId;\n', 'namespace cfh = colorfix::hooks;\nnamespace uxo = colorfix::probe::uxtheme_observer;\nusing cfh::HookId;\n')
rep('bool RegisterWithMinHook(HMODULE module, const char* name, void* hook, void** original) {\n', 'std::vector<void*> g_colorfixTargets;\n\nbool RegisterWithMinHook(HMODULE module, const char* name, void* hook, void** original) {\n')
rep('    const MH_STATUS s = MH_CreateHook(target, hook, original);\n    if (s != MH_OK) {\n        std::printf("setup: MH_CreateHook(%s) = %s\\n", name, MH_StatusToString(s));\n        return false;\n    }\n    return true;\n}\n', '    const MH_STATUS s = MH_CreateHook(target, hook, original);\n    if (s != MH_OK) {\n        std::printf("setup: MH_CreateHook(%s) = %s\\n", name, MH_StatusToString(s));\n        return false;\n    }\n    g_colorfixTargets.push_back(target);\n    return true;\n}\n\nbool EnableColorFixHooks() {\n    for (void* target : g_colorfixTargets) {\n        const MH_STATUS s = MH_EnableHook(target);\n        if (s != MH_OK) {\n            std::printf("setup: MH_EnableHook(ColorFix target) = %s\\n", MH_StatusToString(s));\n            return false;\n        }\n    }\n    return true;\n}\n')
rep('ColorFixProbe increment 5 - hooks + WM_CTLCOLOR + policy + Common Controls v6', 'ColorFixProbe increment 6 - passive UxTheme observation')
rep('    // Phase A: baseline. Hooks created but NOT enabled.\n    MH_STATUS st = MH_Initialize();\n    if (st != MH_OK) { std::printf("setup: MH_Initialize = %s\\n", MH_StatusToString(st)); return 1; }\n    if (!cfh::RegisterPhase1Hooks(RegisterWithMinHook)) return 1;\n', '    // Phase A: initialize MinHook once. UxTheme observation is enabled now,\n    // before any v6 child exists in either order. ColorFix hooks are only\n    // created here and remain disabled until the early/late split below.\n    MH_STATUS st = MH_Initialize();\n    if (st != MH_OK) { std::printf("setup: MH_Initialize = %s\\n", MH_StatusToString(st)); return 1; }\n    if (!uxo::Install(winV, winL)) return 1;\n    if (!cfh::RegisterPhase1Hooks(RegisterWithMinHook)) return 1;\n')
rep('    // Phase B: enable hooks, autotest each one with a direct call.\n    st = MH_EnableHook(MH_ALL_HOOKS);\n    if (st != MH_OK) { std::printf("setup: MH_EnableHook = %s\\n", MH_StatusToString(st)); return 1; }\n', '    // Phase B: enable only ColorFix targets. The passive UxTheme observer has\n    // already been live since before V/L child creation.\n    if (!EnableColorFixHooks()) return 1;\n')
needle = '''    if (late) {\n        SendSysColorChange(winV);\n        SendSysColorChange(winL);\n        Pump(150);\n        afterV = Shoot(winV);\n        afterL = Shoot(winL);\n    }\n\n    // Phase D: dynamic policy.'''
insert = '''    if (late) {\n        SendSysColorChange(winV);\n        SendSysColorChange(winL);\n        Pump(150);\n        afterV = Shoot(winV);\n        afterL = Shoot(winL);\n    }\n\n    // Increment-5 pixel oracle: observation must not change the established\n    // rendering result. Exact colors intentionally make observer passivity an\n    // infrastructure invariant rather than a new rendering expectation.\n    auto shotHas = [](const WindowShot& shot, const RECT& r, COLORREF expected) {\n        for (int m = 0; m < 2; ++m) {\n            COLORREF c = CLR_INVALID;\n            if (shot.mode[m].px.empty() || !SurfaceColor(shot.mode[m], r, &c) || c != expected)\n                return false;\n        }\n        return true;\n    };\n    const bool observerAutotest = uxo::Autotest();\n    bool observerPassive =\n        shotHas(hookV, kV6Surfaces[0].rect, exp3dFace) &&\n        shotHas(hookV, kV6Surfaces[1].rect, RGB(255, 255, 255)) &&\n        shotHas(hookV, kV6Surfaces[2].rect, RGB(253, 253, 253));\n    if (late) {\n        observerPassive = observerPassive &&\n            shotHas(hookL, kV6Surfaces[3].rect, RGB(255, 255, 255)) &&\n            shotHas(afterL, kV6Surfaces[3].rect, expWindow);\n    } else {\n        observerPassive = observerPassive &&\n            shotHas(hookL, kV6Surfaces[3].rect, expWindow);\n    }\n\n    // Phase D: dynamic policy.'''
rep(needle, insert)
rep('    if (!ctlOk) infraOk = false;  // DeleteObject.pass has no valid control\n    if (!policyOk) behaviorOk = false;\n', '    if (!ctlOk) infraOk = false;  // DeleteObject.pass has no valid control\n    if (!observerAutotest || !observerPassive) infraOk = false;\n    if (!policyOk) behaviorOk = false;\n')
needle2 = '''    for (char w : {'V', 'L'}) {\n        const WindowShot& h = w == 'V' ? hookV : hookL;\n        std::printf("v6scenario: %c", w);\n        for (int i = 0; i < kHookCount; ++i) {\n            const long d = h.after.v[i] - h.before.v[i];\n            if (static_cast<HookId>(i) == HookId::DeleteObject) {\n                std::printf(" %s=n/a", kHookNames[i]);\n                continue;\n            }\n            std::printf(" %s=%ld(%s)", kHookNames[i], d, d ? "OBSERVED" : "NOT_OBSERVED");\n        }\n        std::printf("\\n");\n    }\n\n    const int code = !infraOk ? 1 : !behaviorOk ? 2 : 0;\n'''
insert2 = '''    for (char w : {'V', 'L'}) {\n        const WindowShot& h = w == 'V' ? hookV : hookL;\n        std::printf("v6scenario: %c", w);\n        for (int i = 0; i < kHookCount; ++i) {\n            const long d = h.after.v[i] - h.before.v[i];\n            if (static_cast<HookId>(i) == HookId::DeleteObject) {\n                std::printf(" %s=n/a", kHookNames[i]);\n                continue;\n            }\n            std::printf(" %s=%ld(%s)", kHookNames[i], d, d ? "OBSERVED" : "NOT_OBSERVED");\n        }\n        std::printf("\\n");\n    }\n\n    std::printf("\\n[uxtheme observer]\\n");\n    std::printf("uxtheme: passive-pixels %s\\n",\n                observerPassive ? "VALID" : "INFRASTRUCTURE_FAILURE");\n    uxo::PrintReport();\n\n    const int code = !infraOk ? 1 : !behaviorOk ? 2 : 0;\n'''
rep(needle2, insert2)

p.write_text(s, encoding='utf-8', newline='\n')
print('increment 6 probe edits applied')
