from pathlib import Path
p=Path('tests/probe/uxtheme_observer.hpp')
s=p.read_text(encoding='utf-8')
old='''inline bool Autotest() noexcept {\n    return (g_open + g_openForDpi) > 0 && g_themeCount > 0;\n}\n\ninline void PrintReport() {\n    const Stats s = GetStats();\n    std::printf("uxtheme: observer open=%ld open-dpi=%ld draw=%ld draw-ex=%ld color=%ld dropped=%ld %s\\n",\n                s.open, s.openForDpi, s.draw, s.drawEx, s.color, s.dropped,\n                Autotest() ? "PASS" : "INFRASTRUCTURE_FAILURE");\n    const LONG n = g_eventCount < kMaxEvents ? g_eventCount : kMaxEvents;\n    for (LONG i = 0; i < n; ++i) {\n        const Event& e = g_events[i];\n        const wchar_t* klass = ThemeClass(e.theme);\n        if (e.kind == Event::Kind::Color) {\n            std::printf("uxtheme: color class=%ls part=%d state=%d prop=%d\\n",\n                        klass, e.part, e.state, e.prop);\n        } else {\n            std::printf("uxtheme: %s class=%ls part=%d state=%d rect=%dx%d attr=%s\\n",\n                        e.kind == Event::Kind::Draw ? "draw" : "draw-ex",\n                        klass, e.part, e.state, e.width, e.height, e.attribution);\n        }\n    }\n}\n'''
new='''inline bool Autotest() noexcept {\n    return (g_open + g_openForDpi) > 0 && g_themeCount > 0 && g_dropped == 0;\n}\n\ninline bool SameReportedEvent(const Event& a, const Event& b) noexcept {\n    return a.kind == b.kind && a.part == b.part && a.state == b.state &&\n           a.prop == b.prop && a.width == b.width && a.height == b.height &&\n           std::strcmp(a.attribution, b.attribution) == 0 &&\n           std::wcscmp(ThemeClass(a.theme), ThemeClass(b.theme)) == 0;\n}\n\ninline void PrintReport() {\n    const Stats s = GetStats();\n    std::printf("uxtheme: observer open=%ld open-dpi=%ld draw=%ld draw-ex=%ld color=%ld dropped=%ld %s\\n",\n                s.open, s.openForDpi, s.draw, s.drawEx, s.color, s.dropped,\n                Autotest() ? "PASS" : "INFRASTRUCTURE_FAILURE");\n\n    // Keep the CI notice below the ~4 KB annotation limit while preserving\n    // distinct evidence. The fixed buffer still contains every observed event.\n    const LONG themes = g_themeCount < kMaxThemes ? g_themeCount : kMaxThemes;\n    int printedThemes = 0;\n    for (LONG i = 0; i < themes && printedThemes < 8; ++i) {\n        bool duplicate = false;\n        for (LONG j = 0; j < i; ++j)\n            if (std::wcscmp(g_themes[i].klass, g_themes[j].klass) == 0) duplicate = true;\n        if (duplicate) continue;\n        std::printf("uxtheme: theme class=%ls\\n", g_themes[i].klass);\n        ++printedThemes;\n    }\n\n    const LONG n = g_eventCount < kMaxEvents ? g_eventCount : kMaxEvents;\n    LONG printed[24]{};\n    int printedCount = 0;\n    int uniqueSkipped = 0;\n    for (LONG i = 0; i < n; ++i) {\n        const Event& e = g_events[i];\n        bool duplicate = false;\n        for (int j = 0; j < printedCount; ++j)\n            if (SameReportedEvent(e, g_events[printed[j]])) duplicate = true;\n        if (duplicate) continue;\n        if (printedCount == 24) { ++uniqueSkipped; continue; }\n        printed[printedCount++] = i;\n        const wchar_t* klass = ThemeClass(e.theme);\n        if (e.kind == Event::Kind::Color) {\n            std::printf("uxtheme: color class=%ls part=%d state=%d prop=%d\\n",\n                        klass, e.part, e.state, e.prop);\n        } else {\n            std::printf("uxtheme: %s class=%ls part=%d state=%d rect=%dx%d attr=%s\\n",\n                        e.kind == Event::Kind::Draw ? "draw" : "draw-ex",\n                        klass, e.part, e.state, e.width, e.height, e.attribution);\n        }\n    }\n    std::printf("uxtheme: report unique=%d skipped=%d\\n", printedCount, uniqueSkipped);\n}\n'''
if s.count(old)!=1: raise SystemExit(f'target count={s.count(old)}')
s=s.replace(old,new)
s=s.replace('#include <cwchar>\n', '#include <cwchar>\n#include <cstring>\n')
p.write_text(s,encoding='utf-8',newline='\n')
